# Ploty and Dash Overview

What libraries already existto visualize data with python?
- Matplotlib
    - "grandfather" of them all
    - modeled after Matlab plotting capabilities
    - Creates static images
    - Can almost create any type of plot
- Seaborn
    - Uses matplotlib on the backend
    - Designed to create nice looking statistical plots (static plots)
    - Can only create statistical plots available in documentation
- Pandas
    - Main purpose is data analysis
    - Uses matplotlib on the backend through simple .plot() calls
    - Limits scope of plot types
    - static plots

**What is Plotly?**

Plotly ***the company*** foces on data visualization for business intelligence - reporting, dashboards, and hosting BI solutions. Plotly ***the open source library*** is a general data visualization library focused on ***interactive*** visualizations.

Using the plotly python library by itself creates interactive plots as html files. While users can still interact with these plots they cannot be connected to changing data sources. Once the interactive plotly plot is generated, the data the plot represents is "locked in" to the exported state of the plot. You would need to re-reun the py script and re-generate the html file to see any updates. 

**What is Dash?**

Often users want plots to be able to interact with each other, interact with components, or have plots update in real time. To accomplish this level of tasks, we need a dashboard!

Dash is an open-source library from the Plotly company that allows you to create a full dashboard with multiple components, interactivity, and multiple plots. 

Instead of creating an html file, Dash will produce a dashboard web application at a local URL. You can then visit and interact with this dashboard in the web application.

You can then deploy your dashboards online. 

# NumPy Crash Course

NumPy is a scientific computing and mathematical library we will use at time in the course to quickly generate some arrays or matrices of data. 

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]

In [3]:
np.array(mylist)

array([1, 2, 3, 4])

In [4]:
a = np.arange(0,10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.arange(0,10,2)

In [7]:
a

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# random arrays
np.random.randint(0,100)

11

In [12]:
np.random.randint(0,100,(5,5))

array([[88, 79, 20, 44, 22],
       [44,  8, 47, 22, 21],
       [49, 76, 60, 55, 66],
       [32, 92, 42, 72, 43],
       [20, 91, 53, 89, 56]])

In [13]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
np.linspace(0,10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [15]:
np.random.seed(101)

In [16]:
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [18]:
mat = np.arange(0,100).reshape(10,10)

In [19]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
mat[3][7]

37

In [21]:
mat[5,2]

52

In [23]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [24]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [28]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Pandas Crash Course

Pandas is a library built on top of NumPy which allows Python to read in data sets from various formats. 

In [1]:
import pandas as pd

See myexample